apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 1  # Number of instances of the app to run
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: keerthivasanb2025/react-app:latest  # Your Docker image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 80  # Port to forward to the container
  type: LoadBalancer  # Exposes the app externally (Change to ClusterIP if internal only)
